### ISSUE TITLE
Plugin currently unavailable - Runelite change causes plugin build to fail

### ISSUE THREAD

**Issue by robmonte** [adituv/runedoku-plugin#4]
The plugin is currently unavailable to due a Runelite change which causes the plugin to fail to build.

**Comment by adituv** [comment]
Sadly the Runedoku plugin will be unavailable indefinitely as I do not currently have an active Runescape subscription.  If someone who does currently play wants to take over the project and do the necessary refactoring and testing then they can, but unless that happens this plugin will likely remain incompatible.

The change in question is the change to menu entries; the existing code that adds them and hooks into events needs to be removed and replaced with the new MenuEntry interface.  Overall it will lead to better, more reliable code but I am unwilling to update it blindly while I can’t test it.

**Comment by robmonte** [comment]
@adituv I opened a small PR here https://github.com/adituv/runedoku-plugin/pull/5 which isn't a full replacement to the deprecated API but enough that the plugin builds and works. Can you merge? If any other issues come up I'll see what I can do for them, or if others chime in as well.
